### ISSUE TITLE
"Reload" is actually "Provision"

### ISSUE THREAD

**Issue by ryanschmidt** [skycatchfire/drupal-environment#2]
The README refers to reload and provision as interchangeable tasks (https://github.com/skycatchfire/drupal-environment#vagrant-reload). I think it should be explained that this only needs to happen when adding a new site and then the task needs renamed to provision. Reloading can happen without provisioning via `vagrant reload` but if you want to add sites you run this new task. On that note... maybe it's not just provision since that is a vagrant concept. What we're doing here is really just adding new sites so the task should be specifically named to support that.

**Comment by 1forh** [comment]
Would be nice to just have a provision bash script that takes either an `up` or `reload` flag.

**Comment by 1forh** [comment]
something like, `./provision.sh -a up` and `./provision.sh -a reload`

**Comment by 1forh** [comment]
@ryanschmidt 

Adds option/argument flag to bash script: 41948c8ea171a87eb111c15dbabd97f6f6269e04
